#
# 汎用開発環境構築用composeファイル
#
version: '3.6'
services:
  #
  # てきとうな実行コンテナ
  #
  devcon:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    container_name: devcon
    environment:
      - DEBUG=app:*
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: "../"
        target: "/app"
    tty: true

volumes:
  npm_volume:
